"""empty message

Revision ID: 01_initial
Revises:
Create Date: 2022-08-29 19:38:39.748141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cronjobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    weekdays = op.create_table(
        'weekdays',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cron_name', sa.String(length=30), nullable=True),
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('invite_token', sa.String(length=15), nullable=True),
        sa.Column('chat_id', sa.BigInteger(), nullable=True),
        sa.Column('owner_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chat_id'),
        sa.UniqueConstraint('invite_token')
    )
    op.create_table(
        'lectures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=50), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table(
        'user_group',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table(
        'lecture_cronjob',
        sa.Column('lecture_id', sa.Integer(), nullable=False),
        sa.Column('cronjob_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cronjob_id'], ['cronjobs.id'], ),
        sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
        sa.PrimaryKeyConstraint('lecture_id', 'cronjob_id')
    )
    op.create_table(
        'lecture_weekday',
        sa.Column('lecture_id', sa.Integer(), nullable=False),
        sa.Column('weekday_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
        sa.ForeignKeyConstraint(['weekday_id'], ['weekdays.id'], ),
        sa.PrimaryKeyConstraint('lecture_id', 'weekday_id')
    )

    op.bulk_insert(
        weekdays,
        [
            {'id': 1, 'cron_name': 'mon', 'name': 'Пн'},
            {'id': 2, 'cron_name': 'tue', 'name': 'Вт'},
            {'id': 3, 'cron_name': 'wed', 'name': 'Ср'},
            {'id': 4, 'cron_name': 'thu', 'name': 'Чт'},
            {'id': 5, 'cron_name': 'fri', 'name': 'Пт'},
            {'id': 6, 'cron_name': 'sat', 'name': 'Сб'},
            {'id': 7, 'cron_name': 'sun', 'name': 'Вс'}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecture_weekday')
    op.drop_table('lecture_cronjob')
    op.drop_table('user_group')
    op.drop_table('lectures')
    op.drop_table('groups')
    op.drop_table('weekdays')
    op.drop_table('users')
    op.drop_table('cronjobs')
    # ### end Alembic commands ###
